spring:
  application:
    name=rest-udemy-2025
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rest_udemy_2025?useTimezone=true&serverTimezone=UTC
    username: root
    password: Hepta2020#
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
    show-sql: false
    open-in-view: false